### ISSUE TITLE
On initial start there is no "food" for the snake

### ISSUE THREAD

**Issue by allanhaywood** [donno2048/snake#53]
On initial start of the game, there is no food for the snake. You have to intentionally run into a wall and die in order to get food to show up.

**Comment by donno2048** [comment]
Yeah, that was made in order to reduce three bytes, there is no check in the food spawning (before the first wall creation) for whether or not the food is on a wall, and in 1/5 of the cases it'll happen, but don't worry it can happen only for the first food spawn, the next ones will work as expected.
